### ISSUE TITLE
library libssw.so not found

### ISSUE THREAD

**Issue by tianrenmaogithub** [xiezhq/ISEScan#14]
I noticed that the instruction below may be corrected.

'And then copy sswlib.so to the directory of ISEScan and set the search path as:
cp sswlib.so ../ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:libssw.so'

The library name should be libssw.so rather than sswlib.so. And the right way to export the path is:
export LD_LIBRARY_PATH=the_dir_name_rather_than_full_path:$LD_LIBRARY_PATH

Hope it helps.

**Comment by xiezhq** [comment]
Thanks for the comment. I have updated the Readme file accordingly.

Xie
