### ISSUE TITLE
ISEScan-1.7.1 ::  incorrect version number

### ISSUE THREAD

**Issue by EricDeveaud** [xiezhq/ISEScan#17]
hello,

when installing from source version 1.7.1 
when using isescan.py --version iv claims to be 1.5.4

see:
```
bigmess:ISEScan/1.7.1 > isescan.py --version
isescan 1.5.4
```

see version defined in isescan.py
```
# ISEScan version
version = '1.5.4'
```

regards

Eric

**Comment by xiezhq** [comment]
Eric,

Thanks for the comment. I have updated the version number in source code.

Xie
