### ISSUE TITLE
Question about  Results

### ISSUE THREAD

**Issue by lancetxiao** [xiezhq/ISEScan#18]
Dear Xie,
      Thanks for this great IS tools. However, I don't understand the %Genome in the sum results. Because I can not figure out the "dnaLen: length of the specific sequence". What is the "specific sequence"？

**Comment by xiezhq** [comment]
Hi lancetxiao,

ISEScan treat each sequence in a fasta file as an independent genome (DNA sequence). So,
the 'specific sequence' is one DNA sequence, namely, a sequence following a head line starting with '>' in your input fasta file (e.g. the sequence with seqid 'gi|228288719|ref|NC_012624.1|' in NC_012624.fna). It will be clear if you can try running ISEScan on a fasta file containing multiple sequences and have a look at the output file *.sum file.

Xie
