### ISSUE TITLE
ISEScan not available through Bioconda?

### ISSUE THREAD

**Issue by jaipadmakumar** [xiezhq/ISEScan#20]
I'm not sure if this should be posted here or on the Bioconda page but I can't seem to locate the package through Conda. I get a `PackagesNotFoundError` when I try to install with `conda install -c bioconda isescan`. Is this a known issue and, if so, should I just go ahead with a manual install?

**Comment by xiezhq** [comment]
I tried installing ISEScan through bioconda one month ago, it works. I posted all my install steps at https://github.com/xiezhq/ISEScan#Bioconda-install. Could you try it step by step?

If you are familiar with Linux, manual install from source should not be a problem for you. However, please try bioconda first to save your time.

Xie

**Comment by jaipadmakumar** [comment]
Yea that’s the instruction page I followed and no luck (only difference is I have the full anaconda rather than mini conda). 

Are you still able to find it if you just do a conda search for it?

**Comment by xiezhq** [comment]
ISEScan bioconda package is still there. The following are the steps I uninstall and re-install it on my centos machine:
```
[xiezhq@centos7-nat ~]$ conda uninstall isescan
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /apps/inst/miniconda3

  removed specs:
    - isescan


The following packages will be REMOVED:

  biopython-1.76-py37h516909a_0
  blast-2.5.0-hc0b0e79_3
  boost-1.73.0-py37h429e714_0
  boost-cpp-1.73.0-h7b93d67_1
  bzip2-1.0.8-h516909a_2
  fastcluster-1.1.26-py37h0da4684_1
  fraggenescan-1.30-h470a237_2
  hmmer-3.3-he1b5a44_1
  icu-67.1-he1b5a44_0
  isescan-1.7.2.1-h516909a_0
  libblas-3.8.0-14_openblas
  libcblas-3.8.0-14_openblas
  libgfortran-ng-7.5.0-hdf63c60_6
  liblapack-3.8.0-14_openblas
  libopenblas-0.3.7-h5ec1e0e_6
  lz4-c-1.9.2-he1b5a44_1
  numpy-1.18.5-py37h8960a57_0
  perl-5.26.2-h516909a_1006
  scipy-1.4.1-py37ha3d9a3c_3
  zstd-1.4.4-h6597ccf_3


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
[xiezhq@centos7-nat ~]$ isescan.py
bash: isescan.py: command not found...
[xiezhq@centos7-nat ~]$ conda install isescan
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /apps/inst/miniconda3

  added / updated specs:
    - isescan


The following NEW packages will be INSTALLED:

  biopython          conda-forge/linux-64::biopython-1.76-py37h516909a_0
  blast              bioconda/linux-64::blast-2.5.0-hc0b0e79_3
  boost              conda-forge/linux-64::boost-1.73.0-py37h429e714_0
  boost-cpp          conda-forge/linux-64::boost-cpp-1.73.0-h7b93d67_1
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_2
  fastcluster        conda-forge/linux-64::fastcluster-1.1.26-py37h0da4684_1
  fraggenescan       bioconda/linux-64::fraggenescan-1.30-h470a237_2
  hmmer              bioconda/linux-64::hmmer-3.3-he1b5a44_1
  icu                conda-forge/linux-64::icu-67.1-he1b5a44_0
  isescan            bioconda/linux-64::isescan-1.7.2.1-h516909a_0
  libblas            conda-forge/linux-64::libblas-3.8.0-14_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-14_openblas
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.5.0-hdf63c60_6
  liblapack          conda-forge/linux-64::liblapack-3.8.0-14_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.7-h5ec1e0e_6
  lz4-c              conda-forge/linux-64::lz4-c-1.9.2-he1b5a44_1
  numpy              conda-forge/linux-64::numpy-1.18.5-py37h8960a57_0
  perl               conda-forge/linux-64::perl-5.26.2-h516909a_1006
  scipy              conda-forge/linux-64::scipy-1.4.1-py37ha3d9a3c_3
  zstd               conda-forge/linux-64::zstd-1.4.4-h6597ccf_3


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
[xiezhq@centos7-nat ~]$ isescan.py
usage: isescan [-h] [--version] [--removeShortIS] [--no-FragGeneScan]
               [--nthread NTHREAD]
               seqfile path2proteome path2hmm
isescan: error: the following arguments are required: seqfile, path2proteome, path2hmm_
```

Xie

**Comment by jaipadmakumar** [comment]
Ok thanks for double checking. Not sure what the issue but here's the full error for the record:

`Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - isescan

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/bpteague/osx-64
  - https://conda.anaconda.org/bpteague/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
`

This might be a more general problem. It looks like there are others with a similar issue on other packages (https://github.com/conda/conda/issues/9653). Anyways, thanks for the help!

**Comment by xiezhq** [comment]
You can try installing isescan in conda-forge or bioconda channel. The following is my test.

# install isescan with conda
conda create -m  -p test/isescan
source activate /home2/s178588/test/isescan
conda install -c conda-forge isescan
# run isescan
test/isescan/bin/isescan.py

Good luck!
Xie

**Comment by gvalchca** [comment]
Hey, 
I still run into exactly the same problem: "PackagesNotFoundError" on mac. 

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - isescan

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Whereas when I try to install from the source its impossible to install FragGeneScan..
:/

**Comment by xiezhq** [comment]
Hi Anna Gorska,

I have no idea about ISEScan on mac as I only fully tested it on Linux. I knew there is compling issue for FragGensScan on Mac but I once solved it. To solve the problem of running FragGeneScan on Mac, please modify two source files in FragGeneScan source codes: 1) open util_lib.c and comment out ‘#include <malloc.h>’ on line3; 2) open hmm_lib.c and comment out ‘‘#include <malloc.h>’ on line6 and replace values.h with limits.h on line4. The modified FragGeneScan can run on Mac and Linux without problem according to our test result.

Hope it helps!

Xie
________________________________

**Comment by gvalchca** [comment]
Dear Xie, 

thanks a lot for your reply. I have solved it around, just by installing on my linux box (which took 30s and run without issues). I think it would be useful to put some note about possible Mac-problems, cause I spent some hours trying to hunt down this error,

regards,
Anna

**Comment by xiezhq** [comment]
Thank you for the good suggestion, Anna. I will find time to write a FAQ list including the Mac-problem you mentioned.

Best,
Xie

**Comment by xiezhq** [comment]
Update, a section `ISEScan on mac` was added in `Installation` to provide hints for compiling FragGensScan codes on Mac.
