### ISSUE TITLE
Error when running test data

### ISSUE THREAD

**Issue by stanislasmorand** [xiezhq/ISEScan#26]
Dear Xie,
I received an error message when I tried to run the test. 
I manually installed ISEScan and dependencies:
numpy-1.19.2
scipy-1.5.2
fastcluster-1.1.26
FragGeneScan1.30
HMMER-3.3.1
BLAST 2.8.1
biopython-1.78 
I also compiled the SSW library shipped with ISEScan as followed:
```
 cd /home/morands/ISESCAN/ISESSCAN-master/ssw201507
 gcc -Wall -O3 -pipe -fPIC -shared -rdynamic -o libssw.so ssw.c ssw.h
 cp libssw.so ../
 export LD_LIBRARY_PATH=/home/morands/ISESCAN/ISESSCAN-master:$LD_LIBRARY_PATH
```

I updated the constants.py file with appropriate path for the different variables.

Here is the message I received when running the command :
`python3 isescan.py NC_012624.fna proteome hmm --nthread 2`

```
Traceback (most recent call last):
  File "/home/morands/LIBRARIES/numpy-1.19.2/numpy/__init__.py", line 124, in <module>
    from numpy.__config__ import show as show_config
ModuleNotFoundError: No module named 'numpy.__config__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "isescan.py", line 10, in <module>
    import isPredict
  File "/home/morands/ISESCAN/ISEScan-master/isPredict.py", line 15, in <module>
    import pred
  File "/home/morands/ISESCAN/ISEScan-master/pred.py", line 14, in <module>
    import scipy.spatial.distance
  File "/home/morands/LIBRARIES/scipy-1.5.2/scipy/__init__.py", line 61, in <module>
    from numpy import show_config as show_numpy_config
  File "/home/morands/LIBRARIES/numpy-1.19.2/numpy/__init__.py", line 129, in <module>
    raise ImportError(msg)
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

Do you have an idea why there is an issue with the import of numpy?
Thanks in advance for your precious help & time.
Kindest regards. Stan

**Comment by xiezhq** [comment]
Hi Stan,

I don't have idea about this issue with the import of numpy. Based on the error report, it seems something wrong with your python3 environment and/or your numpy install. How did you install numpy and where is it installed on your machine? 

Xie

**Comment by stanislasmorand** [comment]
Dear Xie,
I corrected my $PYTHONPATH environment variable w/ correct export syntaxe. The test passed w/o error.
Thanks again for your prompt reply.
Stan
