### ISSUE TITLE
UnboundLocalError: local variable 'raworfhits' referenced before assignment

### ISSUE THREAD

**Issue by FTouzain** [xiezhq/ISEScan#27]
Here is a bug I obtained on a dataset with isescan 1.7.2 :

 File "/home/touzain/miniconda3/bin/pred.py", line 1807, in clusterIntersect4orf
    raworfhits)
UnboundLocalError: local variable 'raworfhits' referenced before assignment

It seems to be solved by replacing in pred.py line 1806:
	orfhit = ((seqid, bd[0], bd[1], strand), clusterName, evalue4domain, evalue4fullseq, ncopy4tpase,
				raworfhits)

by:
	orfhit = ((seqid, bd[0], bd[1], strand), clusterName, evalue4domain, evalue4fullseq, ncopy4tpase,
				raworfhits4bestEvalue)

Hope it helps. Thank you for the dvpmt.
Best regards

**Comment by xiezhq** [comment]
Thank you, FTouzain!

Xie
