### ISSUE TITLE
Unexpected Insertion Sequence

### ISSUE THREAD

**Issue by vappiah** [xiezhq/ISEScan#29]
Hi, I am trying to find insertion squence in my Mycobacterium uclerans isolated. In other to test the ISEScan tool. I began by feeding the reference genome Agy99.gb to the tool. I got  IS256, IS3, IS30,,ISAS1. But I was expecting IS2404 and IS2606 but they were absent. Am I doing something wrong or my organism is not suitable for your tool? Please advice

Below is the command I used
_isescan.py --nthread 36 Agy99.fasta proteome hmm_

**Comment by xiezhq** [comment]
ISEScan output all identified IS element copies (output both complete and partial copies by default) and tried to assign a family name and cluster name to each identified IS copy. That means there is no specific IS element name assigned by ISEScan. If the specific IS element name is needed for an identified IS copy, we can use the DNA sequence of the identified IS copy to search the external IS element database e.g. ISfinder to get the specific IS element name.  

In your case, you can copy the fastq sequence of the IS copy you are interested in and paste it (only sequence without header line starting with '>') to the input form at https://isfinder.biotoul.fr/blast.php and submit the query by clicking button 'BLAST' on that search page. The returned result page will show you the specific IS element name/family/group for that IS copy you just searched.

As I know that, there is no common IS element naming system in the community though https://isfinder.biotoul.fr is popular. That means you might get different name for the same IS copy (a DNA segment in genome sequence) identified by ISEScan when you search the sequence of the identified IS copy in the different database with the different naming system.

Hope it is clear.

Xie

**Comment by jotes35** [comment]
Thanks Xie.

Its clear now. I implement your suggestion and update you
