### ISSUE TITLE
No IS elements found

### ISSUE THREAD

**Issue by rbeinart** [xiezhq/ISEScan#3]
Hello,

I tried the test data that you include with the download, and the program worked fine. I got a "prediction" directory that has the correct files. 

However, I've now tried this twice, with two different of my own datasets, and no IS elements have been identified in either, and no "prediction" directory is output. It does make "proteome" and "hmm" directories. Is there an error, or is this result real?

I've pasted the results of one run below

Thank you!
-Roxanne-

/n/girguis_lab/Users/rbeinart/Apps/FragGeneScan/FragGeneScan -s /n/girguis_lab/Users/rbeinart/Ciliates/CSS/pangenomics/fasta_files/work$
Using 16 threads.
no. of seqs: 1
Clock time used (by 16 threads) = 0.17 mins
prepare gff file..
Time elapsed: 0 hours 0 minutes and 15 seconds.
isPredict begins at Mon Aug  7 16:45:00 2017

Begin to translate genome into proteome.
Translating genome into proteome for /n/girguis_lab/Users/rbeinart/Ciliates/CSS/pangenomics/fasta_files/working/Methanobacterium_sp_SMA$

Finish translating genome into proteome. Mon Aug  7 16:45:15 2017

Begin to phmmer search against proteome database. Mon Aug  7 16:45:15 2017
Finish phmmer searching clusters.single.faa  against SMA27_proteome/working/Methanobacterium_sp_SMA_27.fasta.faa , output SMA27_hmm/wor$

Finish phmmer searching against proteome database. Mon Aug  7 16:58:05 2017

Begin to profile HMM search against proteome database. Mon Aug  7 16:58:05 2017
Finish Profile HMM searching clusters.faa.hmm  against SMA27_proteome/working/Methanobacterium_sp_SMA_27.fasta.faa , output SMA27_hmm/w$

Finish profile HMM searching against proteome database. Mon Aug  7 17:10:17 2017
isPredict ends at Mon Aug  7 17:10:17 2017
pred begins at Mon Aug  7 17:10:17 2017

Begin addNonORFcopy at Mon Aug  7 17:10:19 2017
hello overlapped orfhits (('JQLY01000001.1', 1438905, 1440226, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 0, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 1439018, 1440184, '+'), 'IS200/IS605_96', 1.4e-133, 1.4e-133, 0, {'orfhits4tpase': [(('JQL$
hello overlapped orfhits (('JQLY01000001.1', 1438926, 1439898, '+'), 'IS200/IS605_96', 8.4e-105, 8.4e-105, 0, {'orfhits4tpase': []})
representative orfhit: (('JQLY01000001.1', 1438926, 1440184, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 3, {'orfhits4tpase': [(('JQLY0$
hello overlapped orfhits (('JQLY01000001.1', 1750535, 1751701, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 0, {'orfhits4tpase': [(('JQL$
hello overlapped orfhits (('JQLY01000001.1', 1750535, 1751738, '+'), 'IS200/IS605_96', 1.5e-137, 1.5e-137, 0, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 1750421, 1751743, '+'), 'IS200/IS605_96', 1.4e-133, 1.4e-133, 0, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 1750443, 1751419, '+'), 'IS200/IS605_96', 8.4e-105, 8.4e-105, 0, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 1750442, 1751739, '+'), 'IS200/IS605_96', 1.6e-71, 1.6e-71, 0, {'orfhits4tpase': []})
representative orfhit: (('JQLY01000001.1', 1750443, 1751738, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 5, {'orfhits4tpase': [(('JQLY0$
hello overlapped orfhits (('JQLY01000001.1', 1858659, 1859955, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 0, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 1858753, 1861625, '+'), 'IS200/IS605_96', 1.5e-137, 1.5e-137, 0, {'orfhits4tpase': [(('JQL$
hello overlapped orfhits (('JQLY01000001.1', 1858661, 1859636, '+'), 'IS200/IS605_96', 8.4e-105, 8.4e-105, 0, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 1858660, 1859955, '+'), 'IS200/IS605_96', 1.6e-71, 1.6e-71, 0, {'orfhits4tpase': []})
representative orfhit: (('JQLY01000001.1', 1858660, 1859955, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 4, {'orfhits4tpase': [(('JQLY0$
hello overlapped orfhits (('JQLY01000001.1', 2068969, 2070264, '-'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 0, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 2068970, 2070171, '-'), 'IS200/IS605_96', 1.5e-137, 1.5e-137, 0, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 2069290, 2070263, '-'), 'IS200/IS605_96', 8.4e-105, 8.4e-105, 0, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 2069020, 2070146, '-'), 'IS200/IS605_96', 1.6e-71, 1.6e-71, 0, {'orfhits4tpase': [(('JQLY0$
representative orfhit: (('JQLY01000001.1', 2068970, 2070263, '-'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 4, {'orfhits4tpase': [(('JQLY0$
hello overlapped orfhits (('JQLY01000001.1', 2171485, 2172460, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 0, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 2171577, 2172460, '+'), 'IS200/IS605_96', 1.5e-137, 1.5e-137, 0, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 2171485, 2172456, '+'), 'IS200/IS605_96', 1.4e-133, 1.4e-133, 0, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 2171577, 2172481, '+'), 'IS200/IS605_96', 8.4e-105, 8.4e-105, 0, {'orfhits4tpase': [(('JQL$
hello overlapped orfhits (('JQLY01000001.1', 2171485, 2172460, '+'), 'IS200/IS605_96', 1.6e-71, 1.6e-71, 0, {'orfhits4tpase': []})
representative orfhit: (('JQLY01000001.1', 2171485, 2172460, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 5, {'orfhits4tpase': [(('JQLY0$
Finish addNonORFcopy at Mon Aug  7 17:10:19 2017
Begin addNonORFcopy1 at Mon Aug  7 17:10:19 2017
hello overlapped orfhits (('JQLY01000001.1', 1438926, 1440184, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 3, {'orfhits4tpase': [(('JQL$
hello overlapped orfhits (('JQLY01000001.1', 1438905, 1440226, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 5, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 1438926, 1439898, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 5, {'orfhits4tpase': []})
representative orfhit: (('JQLY01000001.1', 1438926, 1440184, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 3, {'orfhits4tpase': [(('JQLY0$
hello overlapped orfhits (('JQLY01000001.1', 1750443, 1751738, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 5, {'orfhits4tpase': [(('JQL$
hello overlapped orfhits (('JQLY01000001.1', 1750421, 1751743, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 3, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 1750441, 1751738, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 4, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 1750442, 1751739, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 4, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 1750443, 1751419, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 5, {'orfhits4tpase': []})
representative orfhit: (('JQLY01000001.1', 1750442, 1751738, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 5, {'orfhits4tpase': [(('JQLY0$
hello overlapped orfhits (('JQLY01000001.1', 1858660, 1859955, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 4, {'orfhits4tpase': [(('JQL$
hello overlapped orfhits (('JQLY01000001.1', 1858659, 1859955, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 5, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 1858660, 1859955, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 4, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 1858661, 1859636, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 5, {'orfhits4tpase': []})
representative orfhit: (('JQLY01000001.1', 1858660, 1859955, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 4, {'orfhits4tpase': [(('JQLY0$
hello overlapped orfhits (('JQLY01000001.1', 2068970, 2070263, '-'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 4, {'orfhits4tpase': [(('JQL$
hello overlapped orfhits (('JQLY01000001.1', 2068969, 2070264, '-'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 5, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 2068970, 2070264, '-'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 4, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 2069290, 2070263, '-'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 5, {'orfhits4tpase': []})
representative orfhit: (('JQLY01000001.1', 2068970, 2070264, '-'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 4, {'orfhits4tpase': [(('JQLY0$
hello overlapped orfhits (('JQLY01000001.1', 2171485, 2172460, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 5, {'orfhits4tpase': [(('JQL$
hello overlapped orfhits (('JQLY01000001.1', 2171485, 2172456, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 3, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 2171485, 2172460, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 5, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 2171485, 2172460, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 4, {'orfhits4tpase': []})
hello overlapped orfhits (('JQLY01000001.1', 2171485, 2172460, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 4, {'orfhits4tpase': []})
representative orfhit: (('JQLY01000001.1', 2171485, 2172460, '+'), 'IS200/IS605_96', 3.3e-141, 3.3e-141, 5, {'orfhits4tpase': [(('JQLY0$
Finish addNonORFcopy1 at Mon Aug  7 17:10:19 2017
getFullIS() begins at Mon Aug  7 17:10:19 2017
No tir will be found in the invalid tir search window (org=working fastafile=Methanobacterium_sp_SMA_27.fasta): 1438926-1438926 1440184$
No tir will be found in the invalid tir search window (org=working fastafile=Methanobacterium_sp_SMA_27.fasta): 1750442-1750442 1751738$
No tir will be found in the invalid tir search window (org=working fastafile=Methanobacterium_sp_SMA_27.fasta): 1858660-1858660 1859955$
No tir will be found in the invalid tir search window (org=working fastafile=Methanobacterium_sp_SMA_27.fasta): 2068970-2068970 2070264$
No tir will be found in the invalid tir search window (org=working fastafile=Methanobacterium_sp_SMA_27.fasta): 2171485-2171485 2172460$
No tir will be found in the invalid tir search window (org=working fastafile=Methanobacterium_sp_SMA_27.fasta): 1438926-1438926 1440184$
No tir will be found in the invalid tir search window (org=working fastafile=Methanobacterium_sp_SMA_27.fasta): 1750442-1750442 1751738$
No tir will be found in the invalid tir search window (org=working fastafile=Methanobacterium_sp_SMA_27.fasta): 1858660-1858660 1859955$
No tir will be found in the invalid tir search window (org=working fastafile=Methanobacterium_sp_SMA_27.fasta): 2068970-2068970 2070264$
No tir will be found in the invalid tir search window (org=working fastafile=Methanobacterium_sp_SMA_27.fasta): 2171485-2171485 2172460$
Start removing partial IS elements
Finish removing partial IS elements
Begin removeOverlappedHits at Mon Aug  7 17:10:19 2017
JQLY01000001.1: no intersected hits found
Finish removeOverlappedHits at Mon Aug  7 17:10:19 2017
Begin reading protein database at Mon Aug  7 17:10:19 2017
Finish reading protein database at Mon Aug  7 17:10:19 2017
End in pred Mon Aug  7 17:10:19 2017

**Comment by xiezhq** [comment]
En, it's strange. ISEScan fount some complete or incomplete Transposase genes in your sequence but it seems throw away the Tpase genes in your sequence. Could you send me your sequence to me or put it somewhere to let me download it?

Zhiqun Xie

**Comment by rbeinart** [comment]
Hello,

Thank you for your help with this. I’ve attached the two genome files that I’ve tried. These are archaeal genomes (one complete, one incomplete) from the genus Methanobacterium. Ultimately, I’d also like to try ISEScan on 14 other Methanobacterium genomes if I can!

Best,
-Roxanne-


Roxanne Beinart
Assistant Professor
University of Rhode Island
Graduate School of Oceanography
Coastal Institute Rm 228
215 South Ferry Rd.
Narragansett, RI 02882
401-874-6492
www.roxannebeinart.com
Twitter @SymbiosisRox
Instagram #roxbscience

**Comment by xiezhq** [comment]
Hello Roxanne,

Where is your sequence files you have attached? Or you can give me the web link I can follow and download it.

Xie

**Comment by rbeinart** [comment]
Hi Xie,

Weird, I’m not sure why you can’t see them, as they appear attached to the email on my end. In any case, you can use this link to download them:
https://drive.google.com/open?id=0B0V22mSvbdakeVZVNjYyZXFLcU0 <https://drive.google.com/open?id=0B0V22mSvbdakeVZVNjYyZXFLcU0>

-Roxanne-




Roxanne Beinart
Assistant Professor
University of Rhode Island
Graduate School of Oceanography
Coastal Institute Rm 228
215 South Ferry Rd.
Narragansett, RI 02882
401-874-6492
www.roxannebeinart.com
Twitter @SymbiosisRox
Instagram #roxbscience

**Comment by xiezhq** [comment]
Got it. Thanks.


________________________________

**Comment by xiezhq** [comment]
Hi Roxanne,


I ran ISEScan on your sequences. No problem was found in my test. There are seven and one IS elements identified in  Methanobacterium_sp_SMA_27.fna and CSS_Methanogen_reassembly.fna, respectively. You can find all results in the attached files. The results are put in prediction.test directory. Could you check if there is the prediction.test directory below your working directory where you ran ISEScan?


Thanks,

Xie


________________________________

**Comment by rbeinart** [comment]
Hi Xie,

I re-ran these files, and found they did work, the program is just putting the output files into a sub-directory of the ‘prediction.test’ directory called ‘working’. I either didn’t notice or didn’t look in this before. The ‘prediction.test’ directory existed prior to these runs, since it was created initially when I ran your test dataset (NC_012624.fna). During this initial run, NC_012624 output files ended up directly in the ‘prediction.test’ directory, but that was the first run of ISEScan I had done, so it was when the ‘prediction.test’ directory was made.

So is the program is not creating a new 'prediction’ directory each run? I think I figured it would make a new, unique prediction directory each time (like 'prediction.XX’ if XX.fna is input file).

In any case, thank you for your help, I appreciate it!

-Roxanne-

**Comment by xiezhq** [comment]
Hi Roxanne,


ISEScan will put the results in prediction.test directory (will create one if not exist) and create a sub-directory named by the directory which is the part of the full path of your sequence file. For example, running

python3 isescan.py file1.fna proteome hmm

will put results in prediction.test directory.

BUT

python3 isescan.py genomes/file1.fna proteome hmm

will put results in prediction.test/genomes directory.


If you want isescan create the directory prediction instead of prediction.test, you can change it in constants.py:

1) open constants.py and find the line ending with prediction.test

2) replace prediction.test with prediction in that line

3) save and close constants.py.

4) run ISEScan as usual.

I will change the default result directory from prediction.test to prediction in the next version of ISEScan.


Hope it is clear. If any more question, please let me know.


Best,

Xie


________________________________
