### ISSUE TITLE
Remove hard coded 3rd party dependencies

### ISSUE THREAD

**Issue by oschwengers** [xiezhq/ISEScan#32]
Hi @xiezhq ,
would it be possible to remove the hard coded paths in the `constants.py` to all 3rd party dependencies like `FragGeneScan`, `Blast` and `HMMER`?

This would make it easier to distribute and integrate `ISEScan`. For example, in `BioConda` the required patch file could be removed: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/isescan/constants.patch

For example:
https://github.com/xiezhq/ISEScan/blob/38e37bc066108422ac6bd406df661cd855cc34f0/constants.py#L9

**Comment by xiezhq** [comment]
yes, it can be done. Again, I will implement your suggestions in new version of ISEScan.

**Comment by xiezhq** [comment]
Update, ISEScan v1.7.2.2 and later remove the hard coded 3rd party dependencies, see release history.
