### ISSUE TITLE
Provide results in a standard file format

### ISSUE THREAD

**Issue by oschwengers** [xiezhq/ISEScan#33]
Hi @xiezhq ,
sorry for the flood of issues, but would also be possible to provide the final results (`*.out`) in a standardized file format like `tsv`?

For partial IS elements, the `strand` information is lacking which results in a row with 1 column less than for non-partial hits splitting the row at whitespaces like `str.split()` in python. By using `tab` as a separator, this would not be the case and it'd be much easier to automatically parse the results.

Best regards

**Comment by xiezhq** [comment]
Yes, I agree with you. Either .tsv or .csv will be better solution for the final result files output by ISEScan. I will implement this idea in the next version of ISEScan.

**Comment by xiezhq** [comment]
Update, the ISEScan v1.7.2.2 and later provide `.csv` (using `,` as column separator) and `.tsv` (using `tab` as column separator) files.

**Comment by oschwengers** [comment]
Thanks a lot for this update! I'm quite busy at the moment but I will definitely try this new release soon.
I'll close this for now. Thanks
