### ISSUE TITLE
can not install using bioconda

### ISSUE THREAD

**Issue by wietse1** [xiezhq/ISEScan#34]
dear,

i tried following the steps for bioconda install in a terminal using fedora 29

i receiver nex error when try the install command for ISEscan:

(base) [guest@desktop-bdo3m4f ~]$ conda install isescan
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/guest/miniconda3

  added / updated specs:
    - isescan

The following NEW packages will be INSTALLED:

  biopython          conda-forge/linux-64::biopython-1.78-py38h25fe258_1
  blast              bioconda/linux-64::blast-2.5.0-hc0b0e79_3
  boost              conda-forge/linux-64::boost-1.72.0-py38h1e42940_1
  boost-cpp          conda-forge/linux-64::boost-cpp-1.72.0-h8e57a91_0
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_3
  fastcluster        conda-forge/linux-64::fastcluster-1.1.26-py38hc5bc63f_2
  fraggenescan       bioconda/linux-64::fraggenescan-1.30-h470a237_2
  hmmer              bioconda/linux-64::hmmer-3.3.2-he1b5a44_0
  icu                conda-forge/linux-64::icu-64.2-he1b5a44_1
  isescan            bioconda/linux-64::isescan-1.7.2.1-h516909a_0
  libblas            conda-forge/linux-64::libblas-3.9.0-8_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-8_openblas
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.5.0-h14aa051_18
  libgfortran4       conda-forge/linux-64::libgfortran4-7.5.0-h14aa051_18
  liblapack          conda-forge/linux-64::liblapack-3.9.0-8_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.12-pthreads_hb3c22a3_1
  numpy              conda-forge/linux-64::numpy-1.18.1-py38h8854b6b_1
  perl               conda-forge/linux-64::perl-5.32.0-h36c2ea0_0
  python_abi         conda-forge/linux-64::python_abi-3.8-1_cp38
  scipy              conda-forge/linux-64::scipy-1.5.3-py38h828c644_0

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2020.10.14~ --> conda-forge::ca-certificates-2020.12.5-ha878542_0
  certifi            pkgs/main/noarch::certifi-2020.6.20-p~ --> conda-forge/linux-64::certifi-2020.12.5-py38h578d9bd_1
  openssl                                 1.1.1h-h7b6447c_0 --> 1.1.1j-h27cfd23_0

The following packages will be SUPERSEDED by a higher-priority channel:

  conda               pkgs/main::conda-4.9.2-py38h06a4308_0 --> conda-forge::conda-4.9.2-py38h578d9bd_0

Proceed ([y]/n)? y

Preparing transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/guest/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/guest/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/guest/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/guest/miniconda3/lib/python3.8/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/home/guest/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 317, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/home/guest/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 346, in handle_txn
        unlink_link_transaction.execute()
      File "/home/guest/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 244, in execute
        self.verify()
      File "/home/guest/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/guest/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 221, in verify
        self.prepare()
      File "/home/guest/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 210, in prepare
        grps = self._prepare(self.transaction_context, stp.target_prefix,
      File "/home/guest/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 287, in _prepare
        packages_info_to_link = tuple(read_package_info(prec, pcrec)
      File "/home/guest/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 287, in <genexpr>
        packages_info_to_link = tuple(read_package_info(prec, pcrec)
      File "/home/guest/miniconda3/lib/python3.8/site-packages/conda/gateways/disk/read.py", line 90, in read_package_info
        paths_data = read_paths_json(epd)
      File "/home/guest/miniconda3/lib/python3.8/site-packages/conda/gateways/disk/read.py", line 160, in read_paths_json
        data = json.load(paths_json)
      File "/home/guest/miniconda3/lib/python3.8/json/__init__.py", line 293, in load
        return loads(fp.read(),
      File "/home/guest/miniconda3/lib/python3.8/json/__init__.py", line 357, in loads
        return _default_decoder.decode(s)
      File "/home/guest/miniconda3/lib/python3.8/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/guest/miniconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /home/guest/miniconda3/bin/conda install isescan`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/guest/miniconda3/bin/conda
             CONDA_PREFIX=/home/guest/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/guest/miniconda3/bin/python
               CONDA_ROOT=/home/guest/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               MODULEPATH=/etc/scl/modulefiles:/etc/scl/modulefiles:/usr/share/Modules/modulefil
                          es:/etc/modulefiles:/usr/share/modulefiles
                     PATH=/home/guest/miniconda3/bin:/home/guest/.local/bin:/home/guest/bin:/hom
                          e/guest/.local/bin:/home/guest/bin:/home/guest/miniconda3/bin:/home/gu
                          est/miniconda3/condabin:/home/guest/.local/bin:/home/guest/bin:/usr/sh
                          are/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/guest/miniconda3
            shell level : 1
       user config file : /home/guest/.condarc
 populated config files : /home/guest/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/guest/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/guest/miniconda3/pkgs
                          /home/guest/.conda/pkgs
       envs directories : /home/guest/miniconda3/envs
                          /home/guest/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/5.0.10-200.fc29.x86_64 fedora/29 glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y

regards

**Comment by xiezhq** [comment]
It seems not the ISEScan specific issue. Did you strictly follow the instructions on https://github.com/xiezhq/ISEScan#Bioconda-install? I just followed those install instructions, everything was going well and ISEScan was installed without any issue:

```
(base) [xiezhq@localhost ~]$ which isescan.py
~/miniconda3/bin/isescan.py
(base) [xiezhq@localhost ~]$ ~/miniconda3/bin/isescan.py -h
usage: isescan [-h] [--version] [--removeShortIS] [--no-FragGeneScan] [--nthread NTHREAD]
               seqfile path2proteome path2hmm
...
```
