### ISSUE TITLE
Running isescan on a dataset: missing arguments error

### ISSUE THREAD

**Issue by biflorenzi** [xiezhq/ISEScan#36]
Hello, I am trying to run ISEScan on a dataset of assemblies, using the code advised in 'Tips to run ISEScan efficiently'. The tool works fine on a single assembly and I just did a conda update. The list of assemblies absolute paths is in a file I called prje.fna.list, and give the commands:
nohup cat prje.fna.list | xargs -n 1 -P 2 -I{} isescan.py --seqfile {} --output results --nthread 2 > log.txt &

I immediately get this message:

usage: isescan [-h] [--version] [--removeShortIS] [--no-FragGeneScan]
               [--nthread NTHREAD]
               seqfile path2proteome path2hmm
isescan: error: the following arguments are required: path2hmm
usage: isescan [-h] [--version] [--removeShortIS] [--no-FragGeneScan]
               [--nthread NTHREAD]
               seqfile path2proteome path2hmm
isescan: error: the following arguments are required: path2hmm
usage: isescan [-h] [--version] [--removeShortIS] [--no-FragGeneScan]
               [--nthread NTHREAD]
               seqfile path2proteome path2hmm
isescan: error: the following arguments are required: path2hmm
usage: isescan [-h] [--version] [--removeShortIS] [--no-FragGeneScan]
               [--nthread NTHREAD]
               seqfile path2proteome path2hmm
isescan: error: the following arguments are required: path2hmm

It seems like that the 'usage' shown here is different than the one in the read me (there is no [--output] for instance]) and I see that a new version of the tool has been released recently, could be the problem be related to that? For instance that I still do not have the most recent version (if I ask for an update it tells me that everything is up to date however). 

Thank you in advance for any insight you could give me in this regard! (Apologies if the solution might be obvious, I am only a student and still learning!)

**Comment by xiezhq** [comment]
I updated ISEScan to v1.7.2.2 (https://github.com/xiezhq/ISEScan#Release) which has different command options from the previous version e.g. v1.7.2.1. If you installed ISEScan from conda, the isntalled ISEScan is still prevsious version v1.7.2.1. 

For version v1.7.2.1, please refer to the old readme at https://github.com/xiezhq/ISEScan/tree/v1.7.2.1#Tips to run ISEScan.

The lasted version v1.7.2.2 can be installed manully, and output two more results files .csv and .tsv which are easier for users to read and process the results.

Hope it helps,
Xie

**Comment by xiezhq** [comment]
I am requesting ISEScan update on bioconda but it has not been reviewed and approved by bioconda.

**Comment by biflorenzi** [comment]
Hello Xie,
I see, thank you for your reply! I will use the older options while waiting for the update to be released in conda.

Kind regards,
Bianca

**Comment by xiezhq** [comment]
The new version has been released in bioconda.
