### ISSUE TITLE
Add an array or summary, and maybe a bitmap

### ISSUE THREAD

**Issue by Leytoncito** [xiezhq/ISEScan#37]
It is an excellent tool, and I have already obtained my first conclusions using this tool, however, I have been suffering a bit to represent this analysis in a bitmap, it would be interesting to add an output like this. This is especially useful when ISEScan is launched against many genomes and it is interesting to see the probable presence of some IS. You could add something like what the abricate of tseeman achieves, with the --sumary option.
I have made this wish for my birthday.
Thanks a lot

**Comment by xiezhq** [comment]
It is helpful for users to have a picture summarizing the presence of all IS elements predicted by ISEScan, but it takes time to adding new features in ISEScan. As the alternative solution, ISEScan outputs a table (.sum file) which summarize the IS elements predicted by each sequence in a genome input file. If you put multiple sequences in the input sequence file, ISEScan will summarize the results for each sequence and all sequences from the same input sequence file.

Hope it helps.
