### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by tseemann** [xiezhq/ISEScan#4]
Your instructions say to download `master.zip` but the better way to do this is tag a STABLE release on the "Releases" page, with a version.

Do it here: https://github.com/xiezhq/ISEScan/releases

**Comment by xiezhq** [comment]
Thank you, Torsten. I will try that. Hope you will visit my project page later and give your comments to help improve the ISEScan project.

Xie

**Comment by xiezhq** [comment]
Have the first release (stable) version, v1.5.4.3
