### ISSUE TITLE
Pangenome file such as inputfile

### ISSUE THREAD

**Issue by Leytoncito** [xiezhq/ISEScan#41]
I was wondering ... if it is advisable to use a pangenome file instead of genomes. Technically it works, but: does it make biological sense to do this?.

Thanks in advance.

**Comment by xiezhq** [comment]
It depends. ISEScan is an automated tool to independently detect and annotate IS element and transposases for each of input FASTA sequences. It does not care what kinds of genomes those input sequences are. It is the users of ISEScan to decide whether it make biological sense to do so. If there multiple sequences in the input FASTA file, ISEScan will pick up the first sequence from those sequences and then scan that sequence and detect IS elements in it. After finishing detection of IS elements in the first sequence, it will pick up the second sequence and then scan the second sequence and detect IS elements in it, and so on.

**Comment by Leytoncito** [comment]
Thaks for the reply. In the sense, the file pangenoma.fa, is a fasta file with annotated sequences, including IS. The annotation is not specialized in IS elements. My idea was to corroborate which of these sequences are indeed IS.

**Comment by xiezhq** [comment]
I didn't understand what you mean. Is the pangenoma.fa the input or output of ISEScan? If it is the input file and ISEScan succeeded in running on it, you can get find the predicted IS elements in those outupt files of ISEScan.

**Comment by Leytoncito** [comment]
excuse my English. The pangenome.fa is a result of a pangenomic analysis, it is a multiphase file that gathers all the previously annotated sequences. Since the pangenome is the total grouping of genes from a set of studied genomes, I thought that by using it (pangenome.fa) I can avoid running the ISEScan genome by genome.

**Comment by xiezhq** [comment]
Correct. You can put multiple sequences in one fasta file, then run ISEScan on this fastq file. You will finally find the IS elements predicted for each sequence. 

You might like to know one thing. The current version of ISEScan use FragGeneScan to predict genes (therefore transposases) in the input sequence, the predicted genes might be different from the gene annotations from other gene prediction tools in some cases.

**Comment by xiezhq** [comment]
If your focus is to process lots of sequences, you can also take a look the tips on how to run ISEScan pareallely on your Linux computer, https://github.com/xiezhq/ISEScan#lots-of-genomes.

**Comment by Leytoncito** [comment]
Thanks for the answers, now I am clearer.
