### ISSUE TITLE
different results

### ISSUE THREAD

**Issue by illusion-a** [xiezhq/ISEScan#47]
Hello, I uploaded on ISFinder the genome of a not fully assembled Klebsiella pneumoniae with an evalue value of 1e-5 and I got a result.  However, when I used ISEScan to predict the same genome, I got a very different result, and I didn't understand what was wrong.  My attempts to change the code to get the default or only fully inserted sequences predicted by ISEScan did not solve this problem.  The same problem occurred when predicting fully assembled genomes downloaded from NCBI.  Can you give me some advice?  In addition, I would like to ask if the insertion sequence predicted by ISFinder is the complete insertion sequence?  Forgive me if my question is stupid.  

Below is the command I used  

isescan.py --seqfile KP1.fasta --output results --nthread 8  

isescan.py --seqfile KP1.fasta --output results --nthread 8 --removeShortIS  
Some of the results are shown in the attachment.
Best wishes!

[KP1.txt](https://github.com/xiezhq/ISEScan/files/9483105/KP1.txt)
![20220904013621](https://user-images.githubusercontent.com/112773290/188282260-ca5feca3-37f9-4bcd-be53-7bcd85a8ffa3.png)
[KP1.fasta-ISEScan.xlsx](https://github.com/xiezhq/ISEScan/files/9483113/KP1.fasta-ISEScan.xlsx)

**Comment by xiezhq** [comment]
Hello, 

Did you use ISsaga supported by ISfinder team when you sadi 'the insertion sequence predicted by ISFinder'? I didn't have idea about ISsaga but I would assume its prediction was the complete inerstion sequence if it didn't say something like that.

I quickly checked the first three IS copies listed in 'KP1.fasta-ISEScan.xlsx'. The genes/proteins predicted by FragGeneScan used by ISEScan for the first two might not be good. You might get different/better (probably 'correct') the predictions different from those two listed in KP1.fasta-ISEScan.xlsx if you try to use the gene/protein annotations from NCBI for the genome sequence regions coverred by the first two IS copies in KP1.fasta-ISEScan.xlsx. Please refer to my sugguestion on May 26 on the page at https://github.com/xiezhq/ISEScan/issues/45.

Best,
Xie

**Comment by illusion-a** [comment]
> Hello,
> 
> Did you use ISsaga supported by ISfinder team when you sadi 'the insertion sequence predicted by ISFinder'? I didn't have idea about ISsaga but I would assume its prediction was the complete inerstion sequence if it didn't say something like that.
> 
> I quickly checked the first three IS copies listed in 'KP1.fasta-ISEScan.xlsx'. The genes/proteins predicted by FragGeneScan used by ISEScan for the first two might not be good. You might get different/better (probably 'correct') the predictions different from those two listed in KP1.fasta-ISEScan.xlsx if you try to use the gene/protein annotations from NCBI for the genome sequence regions coverred by the first two IS copies in KP1.fasta-ISEScan.xlsx. Please refer to my sugguestion on May 26 on the page at #45.
> 
> Best, Xie

Thank you very much for your advice
