### ISSUE TITLE
Translated proteome of zero bytes 

### ISSUE THREAD

**Issue by MiloEliot** [xiezhq/ISEScan#49]
Hi! 
I installed ISEScan via bioconda in my mac and I was testing it using the provided dataset. Although it shows that the translation is finished, the search cannot be proceeded because: 

Finish translating genome into proteome. Wed Aug 30 11:48:55 2023
No such file or Empty file test/proteome/NC_012624.fna.faa
No such file or Empty file test/proteome/NC_012624.fna.faa
No hit was returned by HMM search against protein database. Wed Aug 30 11:48:55 2023

I checked the produced proteome files noticing that they are of zero bytes.
<img width="751" alt="Screenshot 2023-08-30 at 12 02 48" src="https://github.com/xiezhq/ISEScan/assets/136127826/8f7ee8fd-4198-4406-ac4c-87c9da21aada">

Could you please provide a solution to this problem? Thanks.

**Comment by xiezhq** [comment]
Hi MiloEliot,

I don't have mac so cannot test it to reproduce your case. To help figure out what happened in your case, I have a few questions.

- Which version of ISEScan did you install on your mac?
- What's the full command when you ran ISEScan in your case?

Xie

**Comment by MiloEliot** [comment]
Hello! Thank you for your swift reply. 
To answer your questions:
1. The version of ISEScan is 1.7.2.3. 
2. The command I used is `isescan.py --seqfile NC_012624.fna --output test_result`

**Comment by xiezhq** [comment]
Please run the command below and send me the log.txt.

**nohup isescan.py --seqfile NC_012624.fna --output test_result > log.txt**

Please run the command below and then show me the output of the command.

**ls -lh test_result**

**Comment by MiloEliot** [comment]
Here is the output: 

miniconda3/envs/ISEScan/bin/FragGeneScan -s NC_012624.fna -o test_result/proteome/NC_012624.fna -w 0 -t illumina_5 -p 1
prepare gff file..
Time elapsed: 0 hours 0 minutes and 0 seconds.
ISEScan starts at Wed Aug 30 19:09:12 2023
predict and translate genes from genome sequence into protein database using FragGeneScan program

Begin to translate genome into proteome.
Translating genome into proteome for NC_012624.fna , return  0

Finish translating genome into proteome. Wed Aug 30 19:09:12 2023
No such file or Empty file test_result/proteome/NC_012624.fna.faa
No such file or Empty file test_result/proteome/NC_012624.fna.faa
No hit was returned by HMM search against protein database. Wed Aug 30 19:09:12 2023
ISEScan ends at Wed Aug 30 19:09:12 2023

**Comment by xiezhq** [comment]
Something is wront with the first step in your ISEScan. I tested running ISEScan, the first part of the output is below:

**/home/xiezhq/miniconda3/bin/FragGeneScan -s NC_012624.fna -o test_result/proteome/NC_012624.fna -w 0 -t illumina_5 -p 1
Using 1 threads.
no. of seqs: 1
Clock time used (by 1 threads) = 0.01 mins
prepare gff file..
Time elapsed: 0 hours 0 minutes and 1 seconds.
ISEScan starts at Tue Aug 29 15:18:25 2023
predict and translate genes from genome sequence into protein database using FragGeneScan program

Begin to translate genome into proteome.
Translating genome into proteome for NC_012624.fna , return  0**

**Comment by MiloEliot** [comment]
Thank you for your answer. I also think something is wrong with FragGeneScan in my case. I tried to run FragGeneScan directly by calling `run_FragGeneScan.pl`. It shows the same result. Do you perhaps know the reason why FragGeneScan fails in Mac and how to solve it? I tried to find **util_lib.c** by following the instruction posted by you, but cannot find the file.

**Comment by xiezhq** [comment]
1. What version of FragGeneScan on your computer? ISEScan requires version 1.30 or earlier.

2. If you want to try solving the FragGeneScan issue by following the instruction posted by me, you need to download source of FragGeneScan, and then modify that file and then compile the souce codes to produce the executable FragGeneScan. Once you get executable FragGeneScan, on your mac, you just need to replace the existing one with this new one you produced.

**Comment by xiezhq** [comment]
The more simple way to do your job is to get a Linux system and install ISEScan via bioconda. That's it. Then, you can focus on your research project and get your job done.

**Comment by MiloEliot** [comment]
Thank you for the suggestion!
