### ISSUE TITLE
pip install ISEScan

### ISSUE THREAD

**Issue by tseemann** [xiezhq/ISEScan#5]
It would be great if you could simplify the install process by making it `pip3` installable.

See https://packaging.python.org/tutorials/distributing-packages/

**Comment by xiezhq** [comment]
Thank you again, Torsten. I will find time to learn and do that in the future. Your comments are appreciated.

Xie

**Comment by tseemann** [comment]
@xiezhq any progress on this?
i think a bioconda would be better.

**Comment by pbasting** [comment]
@tseemann I agree that a bioconda package for ISEScan would be useful. I will attempt to make a bioconda recipe for it myself and I'll comment on this issue with any updates.

**Comment by tseemann** [comment]
This is the recommended steps and channel order for bioconda using miniconda3.
https://bioconda.github.io/user/install.html
