### ISSUE TITLE
Is there anyway to get the name of IS

### ISSUE THREAD

**Issue by famiji** [xiezhq/ISEScan#51]
Thank you for providing such a good tool for local retrieval of IS sequences，it helps me a lot. But I still have a problem. When I read the output, I found that that the result file does not display the name of the inserted sequence, but only displays family and cluster of ISs. Is there a way to obtain the name of the sequence found in the results?

**Comment by xiezhq** [comment]
ISEScan does not provide the name of IS elements. One idea I have is to submit the IS sequence (predicted by ISEScan) to ISfinder database to get the name  of the same or highly homology IS element and thus you can use that name provided by ISfinder.

Xie

**Comment by famiji** [comment]
Although it may be inconvenient, currently it seems that only this method
can truly solve my problem

Zhiqun Xie ***@***.***> 于2023年9月15日周五 21:49写道：
