### ISSUE TITLE
ISEScan

### ISSUE THREAD

**Issue by vilasben** [xiezhq/ISEScan#52]
I am using ISEScan for bacterial genome

I am getting error that
predict and translate genes from genome sequence into protein database using FragGeneScan program

Begin to translate genome into proteome.
/Users/oliverlab/vilas_data/pacbio23/NCBI/3492/ISEScan-1.7.2.3/miniconda3/yes/bin/FragGeneScan -s NC_012624.fna -o results/proteome/NC_012624.fna -w 0 -t illumina_5 -p 2
Using 2 threads.
no. of seqs: 1
prepare gff file..
sh: awk: command not found

Similar error found in test and in our genome.
Thank You
Vilas

**Comment by xiezhq** [comment]
Hi Vilas,

The error message said there was no awk software on your computer. The awk is pre-installed on most of Linux computer. Did you run ISEScan on Linux computer? 

Xie
