### ISSUE TITLE
Merge the sum files for condensed overview and heatmaps

### ISSUE THREAD

**Issue by AhmedElsherbini** [xiezhq/ISEScan#53]
Hello, firstly thanks for your nice tool. I like it :)

For me, as I work with many genomes per run, I  needed a simple feature, which is condensing the sum files into one simple Excel sheet, one overall and one for heatmaps. 

So,

I developed this [simple script](https://github.com/AhmedElsherbini/ISEScan_stats). In two flavors. one that includes the copy number (nIS) for the whole analysis and one script that ignores it (meaning it uses only the first column of the sum file). 
I see in the sum file you sum the copy number as the total number of IS per genomes, does this mean that I shall use (nIS) for heatmaps and exclude the first script? what is your opinion? 

Your feedback is welcome.

**Comment by xiezhq** [comment]
Hi AhmedElsherbini,

I am not sure what you want to know from me. For each ISEScan run, one *.sum file is created per one FASTA file (input file, e.g. NC_012624.fna). If there are multiple sequences in the input file (FASTA file), the column 'nIS' in the final row in .sum file gives the total number of IS element copies identified in all sequences in the input file.

Hope this answered your question.

Xie

**Comment by AhmedElsherbini** [comment]
Okay, thank you for your fast response, so I will keep only the script that includes the (nIS) in the heatmap.
