### ISSUE TITLE
ISEScan Stuck in a Non-responsive State After Running for 30 Hours

### ISSUE THREAD

**Issue by wanghang7410** [xiezhq/ISEScan#55]
Title:
ISEScan Stuck in a Non-responsive State After Running for 30 Hours

Body:
I've been running the following command in ISEScan for about 30 hours, but the program seems to have entered a non-responsive state without producing any output or making further progress. The last output I received is as follows:

```
no significant hit with E-value <= 1e-10 found for k97_999147
no significant hit with E-value <= 1e-10 found for k97_999170
no significant hit with E-value <= 1e-10 found for k97_999210
no significant hit with E-value <= 1e-10 found for k97_999261
no significant hit with E-value <= 1e-10 found for k97_999285
no significant hit with E-value <= 1e-10 found for k97_999368
no significant hit with E-value <= 1e-10 found for k97_999392
no significant hit with E-value <= 1e-10 found for k97_999417
no significant hit with E-value <= 1e-10 found for k97_999418
no significant hit with E-value <= 1e-10 found for k97_999433
no significant hit with E-value <= 1e-10 found for k97_999527
no significant hit with E-value <= 1e-10 found for k97_999559
no significant hit with E-value <= 1e-10 found for k97_999564
no significant hit with E-value <= 1e-10 found for k97_99968
no significant hit with E-value <= 1e-10 found for k97_999689
no significant hit with E-value <= 1e-10 found for k97_999751
no significant hit with E-value <= 1e-10 found for k97_999785
no significant hit with E-value <= 1e-10 found for k97_999806
no significant hit with E-value <= 1e-10 found for k97_999835
no significant hit with E-value <= 1e-10 found for k97_999839
no significant hit with E-value <= 1e-10 found for k97_999844
no significant hit with E-value <= 1e-10 found for k97_999849
no significant hit with E-value <= 1e-10 found for k97_999904
no significant hit with E-value <= 1e-10 found for k97_999924
```

The command I ran is:
```
isescan.py --seqfile /io/fasta/xx.fasta --output /io/isescan/xxx --nthread 8
```

I would like to understand why the program is not responding and how to resolve this issue. Any insights or suggestions would be greatly appreciated.

**Comment by xiezhq** [comment]
If ISEScan keeps printing the message on your screen for different sequences in your xx.fasta (e.g. k97_999849, k97_999904, ...), it indicates the ISEScan is still running. It may take long time for ISEScan to process all sequences in your input file, xx.fasta, if there are lots of sequences in your xx.fasta. If you like to finish ISEScan running earlier for each input file, you can split your xx.fasta (e.g. 1000 sequences included in xx.fasta) into 10 or 100 *.fasta and then run ISEScan against each smaller .fasta file.

**Comment by wanghang7410** [comment]
Thank you for your reply.
The last output occurred after 30 hours of execution, and the subsequent program continued running for another 30 hours without any output, with the CPU remaining idle.

**Comment by flowhub-team** [comment]
![image](https://github.com/xiezhq/ISEScan/assets/99722769/2bf7ac20-edba-4c68-a09b-2577b91dc499)
It seems that the logic in the BLAST section has frozen.

**Comment by xiezhq** [comment]
Could you try:
1. Place only two sequences, k97_999924 and the next sequence (k97_xxx) in your xx.fasta, into your input file, test.fasta.
2. Run ISEScan on the new input file, test.fasta.
3. Let me know the result when ISEScan running completes.

**Comment by wanghang7410** [comment]
I ran the test according to the method you provided, and the original command is stuck

![image](https://github.com/xiezhq/ISEScan/assets/139089723/691d434b-44e9-43d6-89aa-b6b8266ccea0)

I extracted several sequences before and after k97 999990 and re-ran them
 isescan.py --seqfile ./test.fasta --output ./test_out/ --nthread 128
ISEScan starts at Sat Mar 30 01:54:34 2024
predict and translate genes from genome sequence into protein database using FragGeneScan program

Begin to translate genome into proteome.
/FragGeneScan1.31/FragGeneScan -s ./test.fasta -o ./test_out/proteome/./test.fasta -w 0 -t illumina_5 -p 128
Using 128 threads.
no. of seqs: 10
Clock time used (by 128 threads) = 0.01 mins
prepare gff file..
Time elapsed: 0 hours 0 minutes and 1 seconds.
Translating genome into proteome for ./test.fasta , return  0

Finish translating genome into proteome. Sat Mar 30 01:54:35 2024

Begin to phmmer search against proteome database. Sat Mar 30 01:54:35 2024
Finish phmmer searching /ISEScan/pHMMs/clusters.single.faa  against ./test_out/proteome/./test.fasta.faa , output ./test_out/hmm/./clusters.single.faa.test.fasta.faa

Finish phmmer searching against proteome database. Sat Mar 30 01:54:50 2024

Begin to profile HMM search against proteome database. Sat Mar 30 01:54:50 2024
Finish Profile HMM searching /ISEScan/pHMMs/clusters.faa.hmm  against ./test_out/proteome/./test.fasta.faa , output ./test_out/hmm/./clusters.faa.hmm.test.fasta.faa

Finish profile HMM searching against proteome database. Sat Mar 30 01:54:57 2024
pred begins at Sat Mar 30 01:54:57 2024
Warning: no significant hit with E-value <= 1e-10 found for k97_999982
Warning: no significant hit with E-value <= 1e-10 found for k97_999983
Warning: no significant hit with E-value <= 1e-10 found for k97_999984
Warning: no significant hit with E-value <= 1e-10 found for k97_999985
Warning: no significant hit with E-value <= 1e-10 found for k97_999986
Warning: no significant hit with E-value <= 1e-10 found for k97_999990
Warning: no significant hit with E-value <= 1e-10 found for k97_999991
Warning: no significant hit with E-value <= 1e-10 found for k97_999992
Warning: no significant hit with E-value <= 1e-10 found for k97_999993
Warning: no significant hit with E-value <= 1e-10 found for k97_999994
Warning: no significant hit with E-value <= 1e-10 found for k97_999982,k97_999983,k97_999984,k97_999985,k97_999986,k97_999990,k97_999991,k97_999992,k97_999993,k97_999994
End in pred Sat Mar 30 01:54:57 2024
Both complete and partial IS elements are reported.
ISEScan ends at Sat Mar 30 01:54:57 2024

Run is complete

**Comment by flowhub-team** [comment]
![33629b351b90931122a6c827db0504a](https://github.com/xiezhq/ISEScan/assets/99722769/c2e0a291-29a9-4083-bd2b-d2e8b275c372)
![48532bd9a984fdb459f53aba3109e77](https://github.com/xiezhq/ISEScan/assets/99722769/df76c447-560d-457b-a16d-72249ac1f761)
It seems that the BLASTN process is stuck from my perspective.
