### ISSUE TITLE
Running from predicted genes

### ISSUE THREAD

**Issue by gvalchca** [xiezhq/ISEScan#6]
Hi,
I'm trying to run ISEScan for the NC_012624.fna that you provide.
But I'm running into an issue:

```
python3 isescan.py NC_012624.fna proteome hmm
isPredict begins at Mon Mar 26 12:32:00 2018
Skip translating NC_012624.fna into proteome/NC_012624.fna.faa
Skip translating genome into proteome.
Skip phmmer clusters.single.faa against proteome/NC_012624.fna.faa
Skip hmmsearch clusters.faa.hmm against proteome/NC_012624.fna.faa
isPredict ends at Mon Mar 26 12:32:00 2018
pred begins at Mon Mar 26 12:32:00 2018
gi|228288719|ref|NC_012624.1| generated an exception: [Errno 2] No such file or directory: '/l/ncbi-blast/bin/blastn'
Begin addNonORFcopy at Mon Mar 26 12:32:00 2018
Traceback (most recent call last):
  File "isescan.py", line 56, in <module>
    isPredictSingle(args4isPredictSingle)
  File "isescan.py", line 21, in isPredictSingle
    isPredict.isPredict(filelist, path2proteome, path2hmm)
  File "/home/tu/iijgo01/programs/ISEScan-1.5.4.3/isPredict.py", line 282, in isPredict
    pred.pred(args4pred)
  File "/home/tu/iijgo01/programs/ISEScan-1.5.4.3/pred.py", line 2604, in pred
    mOrfHits = addNonORFcopy(mispairs, mOrfHits)
  File "/home/tu/iijgo01/programs/ISEScan-1.5.4.3/pred.py", line 1956, in addNonORFcopy
    if len(copypairs[seqid]) == 0:
KeyError: 'gi|228288719|ref|NC_012624.1|'
```

BLAST is in my path.
What else do I need?

regards,
Ania Gorska

**Comment by xiezhq** [comment]
Did you set the path to your blast (line14, 15 and 16) in constants.py? You need to setup some path variables between line3-25 in constants.py.

Thanks,
Xie

**Comment by xiezhq** [comment]
You can get basic help from https://github.com/xiezhq/ISEScan on how to set the path variables for ISEScan.

If still problem, please let me know.

Xie

**Comment by gvalchca** [comment]
Hi,
yeap, sorry I figured this part out. I was able to run it, but It hasn't detected anything with HMMER. I think its due to the protein detection. Is there any possibility to run it with protein file? 

regards,
Ania

**Comment by xiezhq** [comment]
What do you mean ‘It hasn't detected anything with HMMER’? Could you give me more details about that?

Xie

**Comment by gvalchca** [comment]
Ok, so when I run: 
`python3 isescan.py ai_All_scaffolds.fasta proteome hmm`

the issescan runs the FragGeneScan and returns the following:
`No hit was returned by HMM search against protein database. Tue Mar 27 09:54:15 2018`

In the ".faa" file there are 744589 proteins. When I use another protein prediction tool, I get 2 371 187 proteins. So I wanted to surpass the FragGeneScan and run issescan based on the proteins. To that end I set `translateGenome` to False and run:

` python3 isescan.py extracted_proteins.fa proteome hmm`
But it fails with the following error:

`isPredict begins at Tue Mar 27 10:05:27 2018
Traceback (most recent call last):
  File "/home3/gorska/programs/ISEScan-1.5.4.3/isescan.py", line 56, in <module>
    isPredictSingle(args4isPredictSingle)
  File "/home3/gorska/programs/ISEScan-1.5.4.3/isescan.py", line 21, in isPredictSingle
    isPredict.isPredict(filelist, path2proteome, path2hmm)
  File "/home3/gorska/programs/ISEScan-1.5.4.3/isPredict.py", line 249, in isPredict
    proteome_files = proteinFromNCBI(dnaFiles, path_to_proteome)
  File "/home3/gorska/programs/ISEScan-1.5.4.3/isPredict.py", line 237, in proteinFromNCBI
    tools.gbk2fgs4protein(fnaFile, gbkFile, fgsFile)
  File "/home3/gorska/programs/ISEScan-1.5.4.3/tools.py", line 1430, in gbk2fgs4protein
    gbk = rdGbk(gbkFile)
  File "/home3/gorska/programs/ISEScan-1.5.4.3/tools.py", line 1360, in rdGbk
    fp4gbkFile = open(gbkFile, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'extracted_protein.gbk'`

Regards,
Ania

**Comment by xiezhq** [comment]
I now understand what you mean. You can do surpass the FragGeneScan like what you do (set translateGenome to False) but you need the GeneBank file (e.g. NC_012624.gbk) as well as the DNA sequence file (e.g. NC_012624.fna) in the same directory, namely,  both NC_012624.gbk  and NC_012624.fna must be  in the same directory e.g. /your_path/. You start isescan command with the same style:

python3 isescan.py NC_012624.fna proteome hmm

The above command assumes both NC_012624.fna and NC_012624.gbk are available in your current directory.  The DNA sequence file (e.g. NC_012624.fna) is always required in case of either translateGenome=True (in this case, only NC_012624.fna is required) or translateGenome=False (in this case, both NC_012624.fna and NC_012624.gbk are required). In case of translateGenome=False, what the isescan is going to do is to open the protein file in genebank format (.gbk) and the DNA sequence file in fasta format and then convert the protein file (protein database) in genebank format to the protein file (protein database) in FragGeneScan format.  So, you must convert the protein database file (e.g. extracted_proteins.fa) predicted from your favorite protein prediction tool into the genebank file (e.g. your_sequence_id.gbk) before we release the new ISEScan which is able to utilize the protein file directly.

Hope it is helpful.

Best,
Xie

**Comment by gvalchca** [comment]
Dear Xie,
thanks a lot for your help! 

Ania

**Comment by gvalchca** [comment]
Dear Xie,

I've restructured my data so that there is a .fna and .gbk file with predicted genes. 
However, now I'm running into an error:

```
 python3 isescan.py A_All_2_scaffolds.fna proteome hmm
isPredict begins at Wed Apr  4 15:22:41 2018
Traceback (most recent call last):
  File "/home3/gorska/programs/ISEScan-1.5.4.3/isescan.py", line 56, in <module>
    isPredictSingle(args4isPredictSingle)
  File "/home3/gorska/programs/ISEScan-1.5.4.3/isescan.py", line 21, in isPredictSingle
    isPredict.isPredict(filelist, path2proteome, path2hmm)
  File "/home3/gorska/programs/ISEScan-1.5.4.3/isPredict.py", line 249, in isPredict
    proteome_files = proteinFromNCBI(dnaFiles, path_to_proteome)
  File "/home3/gorska/programs/ISEScan-1.5.4.3/isPredict.py", line 237, in proteinFromNCBI
    tools.gbk2fgs4protein(fnaFile, gbkFile, fgsFile)
  File "/home3/gorska/programs/ISEScan-1.5.4.3/tools.py", line 1431, in gbk2fgs4protein
    if seqid.strip('|').rsplit('|', maxsplit=1)[1] != gbk['accver']:
IndexError: list index out of range
```

btw. If file has a 'fasta' extension it cannot find a 'gbk' file, but I just changed an extenstion, 

Ania

**Comment by xiezhq** [comment]
Dear Ania,

The function in ISEScan to use the protein/gene information in .gbk file was originally used by me to try the protein/gene annotation from the NCBI .gbk file (instead of the protein/gene prediction from FragGeneScan) accompanied by the corresponding DNA sequence file (.fna), but it has not been tested on the comprehensive examples. 
 
Do you mind providing me your DNA sequence file (in fasta format) and protein/gene file (.gbk file) to figure out what happened in your case?

Xie

**Comment by gvalchca** [comment]
Dear Xie,

Im trying to run your tool with the genes predicted by prodigal. I just run prodigal for a small subsample of the scaffolds:



there is a chance there are no ISes in there, but I hope its enough for troubleshooting,

regards,
Ania

________________________
PHD candidate  in Algorithms in Bioinformatics University of Tübingen 
and International Max Planck Research School, Tübingen
Phone: +49-7071-29-70454
ab.inf.uni-tuebingen.de/people/gorska/

**Comment by gvalchca** [comment]
Dear Xie,

I found a reason why no HMM hits were found during the original run. isescan looks for the cluster files in the current directory, not in the directory where the program is executed. I modified the execution of the FragGenePred and the "file4clusterHMM" in constants.

**Comment by xiezhq** [comment]
Happy to hear that.

Xie

**Comment by xiezhq** [comment]
Dear Ania,

Did you solve the problem?

Probably you need to modify the paths of clusters.single.faa and clusters.faa.hmm files in constants.py. You can quickly find where in constants.py to setup these two paths by locating the line '# peptide sequences of single-member clusters, which is used by phmmer in hmmer' and the line '# profile HMMs of multiple-member clusters, which is used by hmmsearch in hmmer'.

Hope it helps.

Xie
