### ISSUE TITLE
what is the file4clusterSeqFile4phmmer 

### ISSUE THREAD

**Issue by Xiaojun928** [xiezhq/ISEScan#8]
Hi Mr. Xie,

I am not sure what are the files of file4clusterSeqFile4phmmer and file4clusterHMM like?
You provided clusters.faa.hmm.NC_012624.fna.faa  and clusters.single.faa.NC_012624.fna.faa in the ISEScan/hmm/, it seems like that they are example files. Could you please let me know where can I get file4clusterSeqFile4phmmer and file4clusterHMM for real data?

Thanks a lot!
Xiaojun

**Comment by xiezhq** [comment]
Hi Xiaojun,

I just found the question you asked in November. 

Both file4clusterSeqFile4phmmer and file4clusterHMM for real data included in ISEScan, they are clusters.single.faa (file4clusterSeqFile4phmmer) and clusters.faa.hmm (file4clusterHMM).

Hope it helps.

Best,
Zhiqun Xie

**Comment by Xiaojun928** [comment]
Dear Zhiqun,

Many thanks for your help.

Best,
Xiaojun

Zhiqun Xie <notifications@github.com> 于2019年1月17日周四 上午10:04写道：
