### ISSUE TITLE
Call isescan

### ISSUE THREAD

**Issue by MichWeb75** [xiezhq/ISEScan#9]
Hi,
I get an error when I want to call isescan. Apparently the path to FragGeneScan/train/illumina_5 is not set correctly. How can I fix this ?

```
 python3 isescan.py NC_002944.2.fasta proteome hmm
isPredict begins at Wed Mar 27 14:52:13 2019

Begin to translate genome into proteome.
ERROR: The file for model parameter [/opt/ngs/FragGetrain/illumina_5] does not exist.

```

**Comment by xiezhq** [comment]
Hi,

Thank you for your interest in our software. To help solve the issue, could you send me your ISEScan configuration file (constants.py)? Which version of FragGeneScan do you have on your computer? Where is run_FragGeneScan.pl on your computer?

Zhiqun Xie
